apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: symfony-dev
  labels:
    app: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: kamp-mariadb
        image: mariadb
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "symfony-dev"
        volumeMounts:
        - name: symfony-mysql-persistent-storage
          mountPath: /var/lib/mysql        
      restartPolicy: Always
      volumes:
      - name: symfony-mysql-persistent-storage
        persistentVolumeClaim:
          claimName: symfony-mysql-pv-claim
