apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: mariadb
  name: mariadb
  namespace: symfony-dev
spec:
  ports:
  - name: mariadb
    port: 3306
    targetPort: 3306
  selector:
    app: mariadb