apiVersion: v1
kind: PersistentVolume
metadata:
  name: symfony-mysql-pv-volume
  namespace: symfony-dev
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data-ssd/kubestorage/symfony-dev/mariadb/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: symfony-mysql-pv-claim
  namespace: symfony-dev
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi