apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  namespace: symfony-dev
  labels:
    app: php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php
        image: docker-compose-otherdata_php
        imagePullPolicy: Never
        ports:
        - containerPort: 9000
        resources: {}
        volumeMounts:
        - mountPath: /var/www/symfony-dev.otherdata.com
          name: php-hostpath0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - hostPath:
          path: /data-ssd/kubestorage/var/www/symfony-dev.otherdata.com/public_html
        name: php-hostpath0