apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: symfony-dev
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: kamp-phpmyadmin
        image: phpmyadmin/phpmyadmin
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: PMA_ARBITRARY
          value: "1"
        - name: PMA_HOST
          value: "kamp-mariadb"
        - name: UPLOAD_LIMIT
          value: "3000000000"