apiVersion: v1
kind: PersistentVolume
metadata:
  name: django-mariadb-pv-volume
  namespace: django
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data-ssd/kubestorage/django-mariadb/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-mariadb-pv-claim
  namespace: django
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
