hostNetwork: true
#
dnsPolicy: ClusterFirstWithHostNet

ingress:
  main:
    enabled: false

persistence:
  config:
    enabled: true
    emptyDir:
      enabled: false
    mountPath: /config
    accessMode: ReadWriteOnce
    size: 20Gi

  downloads:
    enabled: true
    emptyDir:
      enabled: false
    mountPath: /downloads-deluge
    accessMode: ReadWriteOnce
    size: 1000Gi

env:
  ## Optional ENV Vars that can be set.
  ## All values below are the current default values.
  PUID: "1000"
  PGID: "1000"
  TZ: "America/Toronto"
  UMASK_SET: "022"
  DELUGE_LOGLEVEL: "info"

service:
  main:
    # -- Enables or disables the service
    enabled: true

    # -- Make this the primary service (used in probes, notes, etc...).
    # If there is more than 1 service, make sure that only 1 service is marked as primary.
    primary: true

    # -- Override the name suffix that is used for this service
    nameOverride:

    # -- Set the service type
    # type: NodePort

    # -- Provide additional annotations which may be required.
    annotations: {}

    # -- Provide additional labels which may be required.
    labels: {}

    # -- Configure the Service port information here.
    # Additional ports can be added by adding a dictionary key similar to the 'http' service.
    # @default -- See below
    ports:
      http:
        # -- Enables or disables the port
        enabled: true

        # -- Make this the primary port (used in probes, notes, etc...)
        # If there is more than 1 service, make sure that only 1 port is marked as primary.
        primary: true

        # -- The port number
        port: 8112

        # -- Port protocol.
        # Support values are `HTTP`, `HTTPS`, `TCP` and `UDP`.
        # HTTPS and HTTPS spawn a TCP service and get used for internal URL and name generation
        protocol: HTTP

        # -- Specify a service targetPort if you wish to differ the service port from the application port.
        # If `targetPort` is specified, this port number is used in the container definition instead of
        # the `port` value. Therefore named ports are not supported for this field.
        targetPort: 8112

        # -- Specify the nodePort value for the LoadBalancer and NodePort service types.
        # [[ref]](https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport)
        nodePort: 8112
      tcp:
        enabled: true
        port: 6881
        protocol: TCP
        targetPort: 6881  

