apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: media-server
  annotations:
    kompose.cmd: kompose convert --volumes hostPath
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: sonarr
  name: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: sonarr
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: sonarr
    spec:
      containers:
      - env:
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: TZ
          value: America/Toronto
        - name: UMASK_SET
          value: "022"
        image: linuxserver/sonarr
        imagePullPolicy: ""
        name: sonarr
        ports:
        - containerPort: 8989
        resources: {}
        volumeMounts:
        - mountPath: /config
          name: sonarr-hostpath0
        - mountPath: /tv
          name: sonarr-hostpath1
        - mountPath: /kidstvshow
          name: sonarr-hostpath2
        - mountPath: /downloads/
          name: sonarr-hostpath4
        - mountPath: /downloads-deluge/
          name: sonarr-hostpath5
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - hostPath:
          path: /data-ssd/kubestorage/sonarr/config
        name: sonarr-hostpath0
      - hostPath:
          path: /data/media/TV Shows
        name: sonarr-hostpath1
      - hostPath:
          path: /data/media/Kids TV Shows
        name: sonarr-hostpath2
      - hostPath:
          path: /data/media/Downloads/nzbget
        name: sonarr-hostpath4
      - hostPath:
          path: /data/media/Downloads/deluge
        name: sonarr-hostpath5
status: {}
