apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: apache
  name: apache
  namespace: web-hosting
spec:
  type: NodePort
  ports:
  - name: http
    port: 8098
    targetPort: 80
    nodePort: 31579
  - name: https
    port: 44399
    targetPort: 443
    nodePort: 32152
  selector:
    app: apache

status:
  loadBalancer: {}
