apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: phpmyadmin
  name: phpmyadmin
  namespace: web-hosting
spec:
  type: NodePort
  ports:
  - name: http
    port: 8099
    targetPort: 80
  selector:
    app: phpmyadmin