apiVersion: v2
appVersion: latest
dependencies:
- name: common
  repository: https://library-charts.k8s-at-home.com
  version: 4.0.1
description: Valheim dedicated gameserver with automatic update and world backup support
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/valheim
icon: https://raw.githubusercontent.com/lloesche/valheim-server-docker/main/misc/Logo_valheim.png
keywords:
- valheim
kubeVersion: '>=1.16.0-0'
maintainers:
- email: owner@russellhall.co.uk
  name: rust84
name: valheim
sources:
- https://github.com/lloesche/valheim-server-docker
- https://hub.docker.com/r/lloesche/valheim-server
version: 4.0.1
