apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-config
  namespace: media-server
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data-ssd/kubestorage/plex/config"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config
  namespace: media-server
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-data
  namespace: media-server
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2500Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/media"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-data
  namespace: media-server
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2500Gi