apiVersion: v1
kind: Service
metadata:
  namespace: media-server
  annotations:
    kompose.cmd: kompose convert --volumes hostPath
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: radarr
  name: radarr
spec:
  type: NodePort
  ports:
  - name: "7878"
    port: 7878
    targetPort: 7878
  selector:
    io.kompose.service: radarr
status:
  loadBalancer: {}
